# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name_plural': 'Works'},
        ),
        migrations.AddField(
            model_name='purchases',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
